# Generated by Django 4.0.6 on 2022-08-08 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
